export const USER_SIGN_IN_SUCCESSFULLY='USER_SIGN_IN_SUCCESSFULLY';
export const USER_SIGN_OUT_SUCCESSFULLY='USER_SIGN_OUT_SUCCESSFULLY';
export const UPDATE_PROFILE='UPDATE_PROFILE';

export const ADMIN_SIGN_IN_SUCCESSFULLY='ADMIN_SIGN_IN_SUCCESSFULLY';
export const ADMIN_SIGN_OUT_SUCCESSFULLY='ADMIN_SIGN_OUT_SUCCESSFULLY';

export const SEARCH_INITIATED='SEARCH_INITIATED';
export const SEARCH_RESULT_RETRIEVED='SEARCH_RESULT_RETRIEVED';
export const SEARCH_FAILED='SEARCH_FAILED';

export const BEST_PRODUCTS='BEST_PRODUCTS'

export const CART_PRODUCT = 'CART_PRODUCT';
export const INDIVIDUAL_PRODUCT='INDIVIDUAL_PRODUCT';
export const DELETE_CART_PRODUCT = 'DELETE_CART_PRODUCT';

export const PURCHASED_PRODUCT = 'PURCHASED_PRODUCT';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';

export const MY_ORDER = 'MY_ORDER';
export const QUANTITY = 'QUANTITY';
export const DECREASED_QUANTITY = 'DECREASED_QUANTITY'

export const SHOW_SNACKBAR='SHOW_SNACKBAR';
export const CLOSE_SNACKBAR='CLOSE_SNACKBAR';

export const SHOW_PROGRESS_BAR='SHOW_PROGRESS_BAR';
export const STOP_PROGRESS_BAR='STOP_PROGRESS_BAR';

export const CATEGORY_SEARCH_INITIATED='CATEGORY_SEARCH_INITIATED'
export const CATEGORY_RESULT_RETRIEVED='CATEGORY_RESULT_RETRIEVED'
export const CATEGORY_SEARCH_FAILED='CATEGORY_SEARCH_FAILED'

export const VIEW_USERS_INITIATED='VIEW_USERS_INITIATED' 
export const VIEW_USERS_RETRIEVED='VIEW_USERS_RETRIEVED' 
export const ADMIN_DELETE_USER='ADMIN_DELETE_USER'
export const VIEW_USERS_FAILED='VIEW_USERS_FAILED' 
export const SUCCESSFULLY_FETCHED_PRODUCT_STATISTICS='SUCCESSFULLY_FETCHED_PRODUCT_STATISTICS';
export const SUCCESSFULLY_FETCHED_USER_STATISTICS='SUCCESSFULLY_FETCHED_USER_STATISTICS';
export const SUCCESSFULLY_FETCHED_SALES_STATISTICS='SUCCESSFULLY_FETCHED_SALES_STATISTICS'; 
export const ADD_TO_CART='ADD_TO_CART';

export const SIGN_IN_SELLER_INITIATED="SIGN_IN_SELLER_INITIATED"
export const SIGN_IN_SELLER_RETRIEVED="SIGN_IN_SELLER_RETRIEVED"



export const SIGN_UP_SELLER_INITIATED="SIGN_UP_SELLER_INITIATED"
export const SIGN_UP_SELLER_RETRIEVED="SIGN_UP_SELLER_RETRIEVED"
export const SIGN_IN_GOOGLE_NEW_USER='SIGN_IN_GOOGLE_NEW_USER'; 
export const SIGN_IN_GOOGLE_EXISTING_USER='SIGN_IN_GOOGLE_EXISTING_USER'; 


export const FETCH_SELLER_LIST='FETCH_SELLER_LIST';
export const DELETE_ACCEPTED_SELLER='DELETE_ACCEPTED_SELLER';
export const DELETE_REJECTED_SELLER='DELETE_REJECTED_SELLER';
export const ACCEPT_SELLER='ACCEPT_SELLER';
export const REJECT_SELLER='REJECT_SELLER';

export const RATING_INITIATED="RATING_INITIATED"
export const RATING_RETRIEVED="RATING_RETRIEVED"

export const CATEGORY_RESULTS_RETRIEVED="CATEGORY_RESULTS_RETRIEVED"