export const USER_SIGN_IN_SUCCESSFULLY='USER_SIGN_IN_SUCCESSFULLY';
export const USER_SIGN_OUT_SUCCESSFULLY='USER_SIGN_OUT_SUCCESSFULLY';

export const ADMIN_SIGN_IN_SUCCESSFULLY='ADMIN_SIGN_IN_SUCCESSFULLY';
export const ADMIN_SIGN_OUT_SUCCESSFULLY='ADMIN_SIGN_OUT_SUCCESSFULLY';

export const SEARCH_INITIATED='SEARCH_INITIATED';
export const SEARCH_RESULT_RETRIEVED='SEARCH_RESULT_RETRIEVED';
export const SEARCH_FAILED='SEARCH_FAILED';



export const NAVIGATED_CATEGORY='SEARCH_INITIATED';
export const CATEGORY_RESULT_RETRIEVED='SEARCH_RESULT_RETRIEVED';
export const CATEGORY_NAVIGATION_RETRIEVED='CATEGORY_NAVIGATION_RETRIEVED';

export const CART_PRODUCT_RETRIVED = 'CART_PRODUCT_RETRIVED';

export const PURCHASED_PRODUCT_STORED_SUCCESSFULLY = 'PURCHASED_PRODUCT_STORED_SUCCESSFULLY';



export const ADD_TO_CART='ADD_TO_CART';


